import localFont from "next/font/local";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Tangerine, Merienda, Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ['400', '700']
});

const tangerine = Tangerine({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-tangerine',
  weight: ['400', '700']
});

const merienda = Merienda({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merienda',
  weight: ['400', '900']
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} ${tangerine.variable} ${merienda.var}  antialiased bg-gray-900`}
      >
      <Navbar />
        {children}
      <Footer/>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        version="1"
        viewBox="0 0 512 512"
        className="invisible w-0 h-0"
      >
        <defs>
          <linearGradient id="grad5" x1="0%" y1="100%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#DA627D" />
            <stop offset="100%" stopColor="#9A348E" />
          </linearGradient>
        </defs>
      </svg>
      </body>
    </html>
  );
}
