import localFont from "next/font/local";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { Tangerine, Merienda, Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ['400', '700']
});

const tangerine = Tangerine({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-tangerine',
  weight: ['400', '700']
});

const merienda = Merienda({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merienda',
  weight: ['400', '900']
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} ${tangerine.variable} ${merienda.var}  antialiased bg-gray-900`}
      >
        <Navbar />
        {children}
      <Footer/>
      </body>
    </html>
  );
}
